# Model
model:
  name: SMP
  network: DeepLabV3
  encoder: efficientnet-b0
  epochs: 20
  device: cuda
  pretrained: false

# Data
data:
  random_state: null
  background_value: 0
  num_workers: 4
  batch_size: 8
  data_path: ./Vascular_pathologies_data_cropped_128_128
  train_val_indices_path: ./dataloader
  
# Augmentations
aug:
  gaussian_noise:
    prob: 0.3
    std: 0.02
  brightness:
    prob: 0.3
    range: [0.8, 1.2]
  gamma:
    prob: 0.3
    range: [0.5, 1.6]
  affine:
    prob: 0.4
    scale: 0.2
    rotate: 20
    translate: 0.1
  mirror:
    prob: 0.65

# Loss
loss:
  learnable_params: false
  loss_type: UW_loss
  default_param_values: [0.5, 0.5]
  loss_components:
    ce:
      weight: null
    dice:
      weight: [0.5, 1.0]

# Optimizer
optimizer:
  type: AdamW
  params:
    lr: 0.0005
    betas: [0.9, 0.999]
    weight_decay: 0.05

