# Model
model:
  name: Swin_UNet
  patch_size: 8 
  window_size: 16
  epochs: 100
  device: cuda
  pretrained: true

# Data
data:
  random_state: null
  background_value: 0
  num_workers: 4
  batch_size: 16
  data_path: ./Vascular_pathologies_data_cropped_128_128
  train_val_indices_path: ./dataloader
  
# Augmentations
aug:
  gaussian_noise:
    prob: 0.3
    std: 0.02
  gaussian_blur:
    prob: 0.2
    sigma: [0.5, 1.5]
  brightness:
    prob: 0.25
    range: [0.8, 1.2]
  gamma:
    prob: 0.2
    range: [0.7, 1.4]
  affine:
    prob: 0.35
    scale: 0.2
    rotate: 20
    translate: 0.1
  elastic: 
    prob: 0.65 
    alpha: 20 
    sigma: 4
  mirror:
    prob: 0.4

# Loss
loss:
  learnable_params: true
  loss_type: UW_loss
  default_param_values: [0.5, 0.5]
  loss_components:
    ce:
      weight: [1.0, 1.0]
    tversky:
      alpha: 0.7
      beta: 0.7
      weight: [0.5, 1.0]

# Optimizer
optimizer:
  type: SGD
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

